### ISSUE TITLE
OpenRasta Header Cache-Control

### ISSUE THREAD

**Issue by EasyAsABC123** [openrasta/openrasta#13]
Using OpenRasta, all responses are returning with a default Cache-Control of private.

We do not have CacheBrowser set anywhere.

-Note: I am running an older version (not documented) of OpenRasta.

**Comment by serialseb** [comment]
There is indeed no caching support in OR as such. There was the beginning of a package, but that stopped being developed a long time ago.

You should be able to implement your own caching if you wish using a contributor.

I'm closing this, feel free to reopen it if you believe there is an issue that needs fixing.
